### ISSUE TITLE
Document or support self signed certificates

### ISSUE THREAD

**Issue by majormoses** [eheydrick/aws-cleaner#3]
I discovered trying to use this that it will fail with self signed certs for sensu or chef with the following:

```
/usr/local/rbenv/versions/2.2.5/lib/ruby/2.2.0/net/http.rb:923:in `connect': SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (OpenSSL::SSL::SSLError)
    from /usr/local/rbenv/versions/2.2.5/lib/ruby/2.2.0/net/http.rb:923:in `block in connect'
    from /usr/local/rbenv/versions/2.2.5/lib/ruby/2.2.0/timeout.rb:73:in `timeout'
    from /usr/local/rbenv/versions/2.2.5/lib/ruby/2.2.0/net/http.rb:923:in `connect'
    from /usr/local/rbenv/versions/2.2.5/lib/ruby/2.2.0/net/http.rb:863:in `do_start'
    from /usr/local/rbenv/versions/2.2.5/lib/ruby/2.2.0/net/http.rb:852:in `start'
    from /usr/local/rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/chef-api-0.7.0/lib/chef-api/connection.rb:282:in `request'
    from /usr/local/rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/chef-api-0.7.0/lib/chef-api/connection.rb:107:in `get'
    from /usr/local/rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/chef-api-0.7.0/lib/chef-api/resources/search.rb:36:in `query'
    from /usr/local/rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/aws-cleaner-2.0.1/bin/aws_cleaner.rb:72:in `get_chef_node_name'
    from /usr/local/rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/aws-cleaner-2.0.1/bin/aws_cleaner.rb:241:in `block (2 levels) in <top (required)>'
    from /usr/local/rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/aws-cleaner-2.0.1/bin/aws_cleaner.rb:217:in `each'
    from /usr/local/rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/aws-cleaner-2.0.1/bin/aws_cleaner.rb:217:in `each_with_index'
    from /usr/local/rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/aws-cleaner-2.0.1/bin/aws_cleaner.rb:217:in `block in <top (required)>'
    from /usr/local/rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/aws-cleaner-2.0.1/bin/aws_cleaner.rb:207:in `loop'
    from /usr/local/rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/aws-cleaner-2.0.1/bin/aws_cleaner.rb:207:in `<top (required)>'
    from /usr/local/rbenv/versions/2.2.5/bin/aws_cleaner.rb:23:in `load'
    from /usr/local/rbenv/versions/2.2.5/bin/aws_cleaner.rb:23:in `<main>'
```

After testing with a certificate from ACM it works just fine. If we care about supporting self signed then we should add an option otherwise we should document this limitation. 

I am more than willing to create a pr for documentation, I am not sure how I feel on the self signed front with services like ACM or lets encrypt being so readily accessible.

**Comment by eheydrick** [comment]
I'm cool with documenting it. I think given the ease of getting real certs (ACM/Letsencrypt) these days we should encourage using CA signed certs.

**Comment by majormoses** [comment]
@eheydrick totally agree just put in a PR for documenting.
